MARA-26 : 친구 관계 CRU 기능 구현
DDD-Community/mara-server pull request #12
Opened 2024-01-28 04:53 UTC by jhkang1517

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- 사용자 회원 가입시 초대 코드 자동 생성
- 사용자간 친구 관계 CRU 기능 구현

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/domain/friend/*.kt`: 친구 관계 기능 구현을 위한 controller, service, repository, entity, DTO 
- `src/main/kotlin/mara/server/domain/user/*.kt`: 초대 코드 생성, 조회 구현을 위한 수정 
- 'src/main/kotlin/mara/server/util/StringUtil.kt`: 난수 생성을 위한 util 클래스

## 관련 이슈
이 PR과 관련된 이슈: #MARA-26

## 특이 사항/주의 사항
- 친구 맺기 기능 수행시, 단방향이 아닌 양방향으로 레코드가 생성됨
- ex. A사용자가 B사용자과 친구를 맺을시, `A -> B` 관계 레코드와 `B -> A` 레코드 2개 가 생성

## 테스트
다음과 같은 테스트를 수행했습니다:
- 단위 테스트: swagger 3.0 사용 단위 테스트 수행

## 스크린샷/동영상
해당 사항 없음

## 리뷰어 참고 사항
- 현재 로그인 한 사용자 조회 시, `userService`의 `getCurrentLoginUser() `메소드를 사용해서 기능을 구현하였는데, 이 메소드를 사용하는 것이 맞는지 확인 부탁드립니다!

2024-01-28 12:04 UTC, Jiwon-cho requested changes
리뷰헀습니다!

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
> +        return success(1)
따로 필요없는 api 라면 지워도 괜찮을것 같습니다.

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +    @Query("select f from Friendship f where (f.fromUser = ?1 and f.toUser = ?2 and f.isFriend = true) or (f.fromUser = ?2 and f.toUser = ?1 and f.isFriend = true)")
추후에 querydsl 설정이 추가되면 리팩토링 해도 좋을것 같습니다.

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        return "ok"
가독성이나 유지보수성 차원에서 해당 값은 상수화 시켜서 관리하는게 좋을것 같습니다. 
따로 클래스로 빼서 다른곳에서도 사용할 수 있게하거나, 클래스 내에서 전역변수로 두고 사용해도 좋을것 같습니다.

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        return "updated"
createFriendship 의  "ok" 와 동일

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        for (friendship: Friendship in friendshipList) {
친구 관계에 대한 업데이트는 삭제 말곤 없을것 같은데, 따로 업데이트로 처리하는 이유는 왜그런걸까요? form,to 유저를 사용하여 해당 유저들이 연결된 친구관계를 삭제하면 되지 않나해서 질문드립니다. 
만약 친구관계를 삭제한 관계의 경우 다시 일방적으로 관계를 맺지 못하게 하기 위한 플래그로서 해당 컬럼을 두신거라면 그 플로우에 맞는 오퍼레이션이 추가 되야 될것같습니다.

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +    private fun addFriendship(user1: User, user2: User) {
헷갈릴 수 있으니 user1, user2  보다는 fromUser, toUser 로 하는게 어떨까요

2024-01-28 12:04 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        val friendship2 = Friendship(
변수에 2 가 들어간 이유는 무엇일까요?

2024-01-29 03:12 UTC, choipureum commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +    @Query("select f from Friendship f where (f.fromUser = ?1 and f.toUser = ?2 and f.isFriend = true) or (f.fromUser = ?2 and f.toUser = ?1 and f.isFriend = true)")
스펙에 `queryDSL`을 넣으려면 리팩토링 전에 추가하는게 좋지않을까 싶습니당👀

2024-01-29 03:13 UTC, choipureum commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        return "ok"
동의함니다아 매직스트링은 최대한 제거부탁드림당

2024-01-29 03:26 UTC, choipureum commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +            .orElseThrow { NoSuchElementException("해당 초대코드를 가진 사용자가 존재하지 않습니다.") }
[IMO]
서비스 레이어 에러처리는 따로 폴딩 따서 errorMSG Enum으로 분리 후 에러 클래스별로 분리시키는게 오떨까요..!
+ ps) 그리고 컨트롤러 레벨 글로벌 익셉션도 추가되면 좋을 것 같네요..! 
`ExceptionHandler`를 통해서 로깅레벨을 분리해보는 것도 츄천드립니다👍

2024-01-29 03:27 UTC, choipureum approved these changes, later dismissed
너무머쪄

2024-01-29 03:39 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +            .orElseThrow { NoSuchElementException("해당 초대코드를 가진 사용자가 존재하지 않습니다.") }
커스텀 익셉션에 대한 정의에 대해 협의를 아직 하지 않아서 논의 후 따로 브랜치를 따 적용할 예정입니다.

2024-01-29 12:47 UTC, choipureum commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +            .orElseThrow { NoSuchElementException("해당 초대코드를 가진 사용자가 존재하지 않습니다.") }
얼른 그럼 티켓따주세요오 어지러워요🙀 우선순위 높아보입니다아

2024-01-29 12:50 UTC, choipureum commented
그리고 PR 템플릿에 이슈번호 #MARA-26 이라고 적혀있는데 이렇게 추가는 오떠세요
이전 FE에 레포에 리뷰드린 내용입니다

## 요구사항

이슈번호: [Mara-32](https://alsehf0316.atlassian.net/browse/MARA-32)

2024-01-31 01:16 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +    @Query("select f from Friendship f where (f.fromUser = ?1 and f.toUser = ?2 and f.isFriend = true) or (f.fromUser = ?2 and f.toUser = ?1 and f.isFriend = true)")
해당건 Jira MARA-41번 이슈 등록했습니다!

2024-01-31 01:18 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipController.kt
> +        return success(1)
삭제하였습니다! 🚫

2024-01-31 01:20 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        val friendship2 = Friendship(
메소드 추출시에 남겨진것 같습니당 삭제했습니다! 🚫

2024-01-31 01:24 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +    private fun addFriendship(user1: User, user2: User) {
`createFriendship` 에서 관계 데이터가 from, to 와 to, from 으로 두 번 적재가 되는데, `addFriendship` 에서 `fromUser`, `toUser`로 변수명을 사용하게 되면 `addFriendship` 메소드 해석시 헷갈릴 수 있다고 판단했습니다. 일반적으로 코드 분석시 `createFriendship`을 먼저 확인하고 그다음 `addFriendship` 으로 메소드를 탐색하기 때문에, `user1`, `user2`가 더 적절할 것으로 판단됩니다.

2024-01-31 01:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +            .orElseThrow { NoSuchElementException("해당 초대코드를 가진 사용자가 존재하지 않습니다.") }
해당건 Jira MARA-49 이슈 등록되어있음을 확인, 별다른 조치하지 않겠습니당

2024-01-31 01:36 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        for (friendship: Friendship in friendshipList) {
가장 먼저 `DeleteMapping`을 사용하게 되면 현재 저희가 사용하는 spring 3.x 버전에서는 `@RequestBody `를 지원하지 않기에 `RequestParam`으로 친구의 `userId`가 노출될 것으로 예상되어 `PutMapping`을 사용하였습니다.

구현 의도 자체는 말씀하신대로 일방적으로 관계를 맺지 못하게 하기 위해서 남겨두는 것이고, 해당 부분은 `createFriendship` 에 플로우를 추가하도록 하겠습니다! 🌱

2024-01-31 01:37 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        return "ok"
클래스 내에 전역 변수로 처리했습니다!! ⚡⚡

2024-01-31 01:37 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        return "updated"
클래스 내에 전역 변수로 처리했습니다!! ⚡⚡

2024-01-31 01:45 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        for (friendship: Friendship in friendshipList) {
다만... 회사에서도 그렇고 DeleteMapping 대신에 PostMapping 기능을 사용하여 삭제 처리를 하는 레퍼런스도 꽤 많은 것으로 알고있어서, 구현시 그러한 방법도 고려해보겠습니다! 💡

2024-01-31 13:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        for (friendship: Friendship in friendshipList) {
`updateFriendship` -> `deleteFriendship` 메소드명 변경 및 기능 재구현 하였습니다! 💪💪

2024-01-31 13:50 UTC, Jiwon-cho approved these changes
수고하셨습니다~

2024-01-31 13:50 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipService.kt
> +        for (friendship: Friendship in friendshipList) {
친구 아이디 노출 떄문에 아이디를 숨기는것도 좋은것 같습니다.

2024-01-31 13:51 UTC, merged