Mara 40 : 나눔 CRUD 구현
DDD-Community/mara-server pull request #13
Opened 2024-01-29 15:35 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- 나눔 게시글 생성, 조회, 수정, 삭제 
- 나눔 신청, 조회

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/domain/share/**`: 나눔 도메인을 위한 클래스

## 관련 이슈
이 PR과 관련된 이슈: #40 MARA-40

## 리뷰어 참고 사항
- 예외 처리 및 커스텀 예외 처리는 따로 이슈를 따 해당 브랜치에서 작업할 예정이기 때문에, 본 PR 에 적은 예외 처리들 그때 리팩토링 예정.

2024-01-30 00:19 UTC, choipureum commented
근데 전체적으로 `pagination`은 고려안된건가유?

2024-01-30 00:24 UTC, Jiwon-cho commented
페이징 처리 필요할것 같아서 기획안 보고 수정해야될것 같네유

2024-01-30 14:48 UTC, jhkang1517 requested changes
고생하셨습니다..! 💪

나눔 글 작성자 화면설계서가 아직은 완성되지 않은 것 같아서 향후에도 수정이 일어날 도메인인건 분명해 보입니다.. 🤒

리뷰는 완료했고, 질문도 섞여 있으니 편하게 답변주세요! 🫡

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
> +interface ApplyShareRepository : JpaRepository<ApplyShare, Long> {
영어는 저보다 잘 아시겠지만.. `ShareApply` 와 `ApplyShare` 중 `ApplyShare`가 더 문법적으로 올바른가요? 한국어로는 그냥 `신청나눔` 으로 읽혀서 여쭤봅니당 🤔

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
> +    fun findAllByUser(user: User): List<ApplyShare>?
저는 `List<ApplyShare>?` 처럼 `?`를 붙이면 예외처리(`orThrowException`)가 안되서 `Optional<>`를 사용했는데, 둘 중 어떤 방식이 더 적합한가요?

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +    @JoinColumn(name = "refrigIngrId")
`refrigIngrId` 컬럼명은 ErdCloud 에 있는 컬럼명을 사용하신 것으로 보이는데요..! 저는 우선 다 풀어서 `ingredientDetailId` 를 사용하고 있습니다! 동작상 문제는 없겠지만 우선 풀어서 가시고, 컬럼명은 추후에 한번 논의를 해서 명확하게 정하는게 좋을 것 같습니다!

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +enum class ShareStatus(@JsonValue val statusValue: String) {
만약 저도 enum 사용시, entity 내부에서 정의하여 사용하는 것으로 하겠습니다! 좋은 방식인 것 같습니다!

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +data class ApplyShare(
Entity도 하나에서 사용이 가능하다면 상관은 없지만... 그래도 테이블 단위니까 파일을 구분하는게 어떨까요?

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +data class UpdateShareRequest(
질문입니다! 보통 `updateRequest` 같은 성격을 지닌 DTO는 `null`을 허용해주는 것이 일반적인가요? 앞단에서 데이터가 어떻게 넘어오는지를 잘 몰라서 여쭤봅니다.. 저는 게시글 수정시 기존 내용이 그대로 넘어오는 것으로 추측하고 있어서요!

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +    private val deleted = "deleted"
이 부분(`deleted`)이 푸름이가 말한 추후 분리되어야 하는 부분인가요??

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +            limitDatetime = shareRequest.limitDate.atTime(shareRequest.limitTime),
성능상 큰 문제는 없겠지만, `shareRequest.limitDate` 가 `limitDate`와 `limitDatetime` 둘 다에서 사용되니 변수 하나로 사용하는건 어떠신가요? ✒️✒️

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +    fun deleteApply(applyId: Long): String {
`deleteApply` -> `deleteApplyShare` 가 통일적인 측면에서 적절해보입니다!

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +        val refrigIngrId = updateShareRequest.refrigIngrId
변수명은 되도록 기존 도메인에서 사용하는 방식대로 풀어서 작성해주시면 좋을 것 같습니다! ingrementDetail 로 현재 도메인 사용중이니, 길다고 생각하시더라도 우선은 통일하시고 나중에 한번에 수정하는 것이 더 좋을 것 같습니다.

2024-01-30 14:48 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +                ingredientDetailRepository.findIngredientDetailByIngredientDetailIdAndIsDeletedIsFalse(ingrId)
1. 나눔게시글 등록 (사과  5개)
2. 내 냉장고 식재료 수정 (사과 5개 -> 10개)
3. 나눔게시글 수정 (사과 5개 -> 10개)

위와 같은 프로세스를 위해 있는 API 일까요?

2024-01-31 14:02 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
> +interface ApplyShareRepository : JpaRepository<ApplyShare, Long> {
1차원적으로 erd cloud 에 올라가있는걸 그대로 사용한것도 있지만, 문법적으로 따졌을 땐, apply for share 나 Share application
써야하는데 너무 긴것 같아 그냥 applyShare 로 했습니다.

2024-01-31 14:06 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +data class ApplyShare(
디렉토리를 도메인 별로 모은것 처럼, 연관관계가 있는 엔티티도 같이 모아놓으면 편할것 같아서 코드 처럼 작성했습니다. 분리하는건 쉽기 때문에 작업하는데에는 문제가 되지는 않지만, 이 관점에서 볼때 어떻게 생각하시는지 궁금합니다.

2024-01-31 14:07 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +    private val deleted = "deleted"
네 맞습니다. 추후 분리 예정입니다.

2024-01-31 14:09 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +data class UpdateShareRequest(
저는 필요한 컬럼의 데이터들만 보내줄수도 있다고 생각해서 null 을 허용 했지만 모든 값이 무조건 다 넘어와서 처리가 된다면 null을 허용할 필요는 없는것 같습니다.

2024-01-31 14:53 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +    @JoinColumn(name = "refrigIngrId")
반영했습니다.

2024-01-31 14:53 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +    fun deleteApply(applyId: Long): String {
반영했습니다.

2024-01-31 14:53 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +        val refrigIngrId = updateShareRequest.refrigIngrId
반영했습니다.

2024-01-31 14:55 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ApplyShareRepository.kt
> +    fun findAllByUser(user: User): List<ApplyShare>?
코틀린 에서는 ? 를 사용해서 체크하는게 조금 더 일반적인것 같습니다.

2024-01-31 14:57 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +            limitDatetime = shareRequest.limitDate.atTime(shareRequest.limitTime),
시간과 날짜가 각각 넘어오기도 하고, 조회 할때 추후 날짜별로 조회 될 때 값이 있으면 더 용이 할꺼 같기도해서 따로 두는게 낫지 않나 생각합니다.

2024-01-31 15:02 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +                ingredientDetailRepository.findIngredientDetailByIngredientDetailIdAndIsDeletedIsFalse(ingrId)
올리는 식재료가 바뀌었을 때 나눔글과 엮이는 식재료를 변경 하는 로직입니다.

그런데 해당 질문에 답하면서 생각해보니, 본인이 사과 10개를 가지고 있다고 하더라도, 꼭 모든 사과를 한번에 다 올려야만 하는게 아니기 때문에, 나눔글에서 선택한 식재료를 몇개올릴 지에 대한 컬럼과, 올리는 식재료의 개수는 실제 식재료가 있는 수를 넘기지 못하게 막는 로직, 올린 수 만큼 전체 수에서 빠지고 취소되면 다시 원복되는 로직등이 추가 되야 될것 같습니다.

이에 대해서 어떻게 생각하시는지 의견 부탁드립니다.

2024-02-01 05:49 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +data class ApplyShare(
제 기준에선 엔티티는 실제로 DB에 구현되는 단위고, DB에서는 분명하게 물리적으로 분리되어 있는 테이블들이기 때문에 분리되는 것이 좋을 것 같습니다!

2024-02-01 05:51 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +            limitDatetime = shareRequest.limitDate.atTime(shareRequest.limitTime),
테스트시에 `limitTime`과 `limitDatetime` 간의 데이터 차이는 없었나요? 초단위까지는 아니라서 차이가 날 것 같지는 않은데.. 혹시나 데이터가 달라질까해서 드린 얘기입니다.

2024-02-01 05:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +                ingredientDetailRepository.findIngredientDetailByIngredientDetailIdAndIsDeletedIsFalse(ingrId)
현재 기획상에서 수량이 나눔글을 작성할때 사용되는 것 같지는 않습니다. 다만... 나눔글이 올라가고, 나눔 신청을 한 사용자들이 존재하는 상황에서, 나눔 글에 있던 식자재를 수정하면 ... 수정 알림도 보내야하고 고려할 사항이 좀 많아 보이네요..

2024-02-01 06:02 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +                ingredientDetailRepository.findIngredientDetailByIngredientDetailIdAndIsDeletedIsFalse(ingrId)
음 이 부분은 제가 확인을 잘 못했네요. 그냥 논리적으로 생각할 때, 전체 수량을 무조건 한번에 다 넣어야만 한다고 생각을 못해서 했던 얘긴데, 일단은 기획 대로 가고 이 부분에 대해서는 한번 얘기를 나눠보는게 좋을것 같습니다. 일단 이 pr 에서는 그냥 기획 대로 가고, 차후 기획이 변경 되거나 변경 사항이 있으면 새 이슈 따서 작업하겠습니다.

2024-02-02 15:20 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/Share.kt
> +data class ApplyShare(
분리했습니다.

2024-02-02 15:20 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
> +            limitDatetime = shareRequest.limitDate.atTime(shareRequest.limitTime),
네 값은 차이 없습니다.

2024-02-03 01:45 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +data class UpdateShareRequest(
이건 FE 분들과 얘기해보면 될 것 같습니다!

2024-02-03 01:45 UTC, jhkang1517 commented
고생하셨습니다 👏👏👏

2024-02-03 01:46 UTC, jhkang1517 approved these changes

2024-02-03 01:50 UTC, merged