로그인 시 계정 정보 없으면 필요한 정보 리턴, 보드 제거
DDD-Community/mara-server pull request #22
Opened 2024-02-03 08:00 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- (여기에 작업한 내용에 대한 자세한 설명을 적어주세요)
- ...

## 변경 사항
- user/** 
- auth/kakaoApiClient,googlApiClient

## 관련 이슈
이 PR과 관련된 이슈: [MARA-번호](https://alsehf0316.atlassian.net/browse/MARA-48)

## 특이 사항/주의 사항
- google login 는 dns 적용 되야 클라우드 서버 에서 테스트 가능

2024-02-04 08:01 UTC, jhkang1517 requested changes
리뷰 완료했습니다! 코멘트 확인 후 답변해주시면 감사하겠습니다! 🌳🌳

2024-02-04 08:01 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +enum class Profile(@JsonValue val profileValue: String) {
`enum class Profile` -> `enum class ProfileImage` 가 좋을 것 같습니다! 🫡

그리고.. 코드성 데이터이니만큼 굳이 `@JsonValue val profileValue: String` 를 사용해서 소문자로 처리 하지 말고, @Enumerated(EnumType.STRING) 를 대문자 그대로 Enum을 String으로 사용하시는건 어떠신가요?

```
@Enumerated(EnumType.STRING)
var profileImage: Profile,
```

```suggestion
enum class Profile() {
    BLUE
    RED,
    YELLOW,
    GREEN,
```

2024-02-04 08:01 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun kakaoLogin(@RequestParam(value = "code") authorizedCode: String): CommonResponse<Any> {
`JwtDto` 에서 `CommonResponse<Any>` , 여기서 `Any`를 사용하신 이유가 있으실까요? 🧐🧐

2024-02-04 08:01 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
>          val infoResponse = kakaoApiClient.requestOauthInfo(accessToken)
`infoResponse` -> `oauthInfoResponse` 로 구체화하는건 어떠신가요?

2024-02-04 12:51 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/User.kt
> +enum class Profile(@JsonValue val profileValue: String) {
좋은것 같습니다. 변경했습니다.

2024-02-04 12:52 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun kakaoLogin(@RequestParam(value = "code") authorizedCode: String): CommonResponse<Any> {
리턴 되는 형태가 두가지 상황에 다른 값(JwtDto, UserResponse) 을 받아야 해서 변경 했습니다.

추가적으로 리프레쉬 토큰 값을 유지하기 위해  Redis 를 사용할까 하는데 어떻게 생각하시는지 의견 부탁드립니다.

2024-02-04 12:52 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserService.kt
>          val infoResponse = kakaoApiClient.requestOauthInfo(accessToken)
반영하였습니다.

2024-02-04 14:51 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun kakaoLogin(@RequestParam(value = "code") authorizedCode: String): CommonResponse<Any> {
Redis가 인메모리를 사용한다고 알고 있어서 부족한 저희 서버 스펙으로 살짝 걱정이 되긴 하는데.. 큰 문제 없으면 구현하고 싶은 기술로 하시는게 좋을 것 같다는 입장입니다! 💪💪

2024-02-04 15:45 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun kakaoLogin(@RequestParam(value = "code") authorizedCode: String): CommonResponse<Any> {
크게 문제가 생길꺼 같지는 않을것 같습니다. 이부분은 클라우드 ssh 접속 하여 작업도 해야하고 콘솔에 로그인하여 작업도 해야해서, 아예 새롭게 브랜치를 따서 작업하겠습니다. 이 부분 외에 수정 할 부분 없으면 승인 해주시면 감사하겠습니다!

2024-02-06 12:12 UTC, jhkang1517 approved these changes

2024-02-06 12:12 UTC, merged