Mara 56
DDD-Community/mara-server pull request #24
Opened 2024-02-12 15:57 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- Redis 를 사용하여 RefreshToken 을 관리하는 기능 개발
 - [x] gradle Redise 디펜던시 추가
 - [x] Redis 설정, RefreshToken 객체, Repository 추가
 - [x] refreshToken 생성 로직 변경
 - [x] refreshToken 을 사용하여 accessToken 갱신 메소드 개발
 - [x] validation 기능 개발

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/config/redis/*.kt`: redis, refreshToken 설정 추가
- `src/main/kotlin/mara/server/domain/user/*.kt`: refreshToken 관련 로직 수정

## 관련 이슈
이 PR과 관련된 이슈: [MARA-56](https://alsehf0316.atlassian.net/browse/56)

## 테스트
다음과 같은 테스트를 수행했습니다:
- 단위 테스트: swagger 사용 단위 테스트 수행

2024-02-13 13:45 UTC, jhkang1517 requested changes
회의 내용 요약드립니다..! 💪💪

```mermaid
graph TD;
    시작["API 호출"] --> 조건1{AccessToken이 유효한가?};
    조건1 -- Yes --> 수행5["정상 호출"] --> 종료;
    조건1 -- No --> 조건2{RefreshToken이 유효한가?};;
    조건2 -- Yes --> 수행3["신규 AccessToken 발급"] --> 수행5["정상 호출"] --> 종료;
    조건2 -- No --> 에러["예외 발생"];
	종료["응답 반환, Header에 AccessToken, RefreshToken 넣어 반환"]
```

2024-02-13 13:45 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    @PostMapping("/accessToken")
`/accessToken` 대신 `/access-token` 건의 드립니다! 🌱🌱

2024-02-13 13:45 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +    fun refreshAccessToken(refreshToken: RefreshAccessTokenRequest): JwtDto {
`AccessToken`을 새로 발급하는 의미에서 `generateAccessToken` 으로 건의 드립니다..! 🌿🌿

2024-02-13 13:45 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val refreshToken = refreshTokenRepository.save(RefreshToken(UUID.randomUUID().toString(), user.userId, 20000))
`20000`은 아래 `token.updateExpiration(20000)`에서도 사용되니 `access-duration-mils` 처럼 `refresh-duration-mins` 로 설정 분리하는건 어떨까요? 🧐🧐

2024-02-13 13:45 UTC, jhkang1517 commented on src/main/resources/application-dev.yml
> -
`\n` 다시 넣어주세요! 🦘🦘

2024-02-14 02:09 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +    fun refreshAccessToken(refreshToken: RefreshAccessTokenRequest): JwtDto {
처음에 generateAccessToken  로 만들었지만 해당  메소드의 목적이 이미 생성된 accessToken 을 갱신 하기  때문에   refreshAccessToken 으로 만들었습니다. 본 관점에서 해당 메소드 이름은 어떤지 의견 부탁드립니다.

2024-02-14 07:20 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +    fun refreshAccessToken(refreshToken: RefreshAccessTokenRequest): JwtDto {
갱신이라는 의미를 저는 라이센스를 갱신하듯 `유효기간의 연장`의 의미라 생각하여 부적절하다고 생각했는데, `갱신토큰(refreshToken)을 사용해서 접근토큰(accessToken)을 갱신한다`는 흐름으로 생각해보니 AccessToken을 갱신한다는 의미로도 이해가 가능할 듯 싶습니다. 현상 유지 해도 괜찮을 것 같습니다. 💡💡

2024-02-15 08:00 UTC, Jiwon-cho commented on src/main/resources/application-dev.yml
> -
적용했습니다.

2024-02-15 08:00 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val refreshToken = refreshTokenRepository.save(RefreshToken(UUID.randomUUID().toString(), user.userId, 20000))
적용했습니다.

2024-02-15 08:01 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    @PostMapping("/accessToken")
로직을 변경하면서 필요없어져서 삭제하였습니다.

2024-02-15 08:40 UTC, Jiwon-cho commented
> # Pull Request
> ## 작업 내용
> 이 PR은 다음과 같은 작업을 포함하고 있습니다:
> 
> * Redis 를 사용하여 RefreshToken 을 관리하는 기능 개발
> * [x]  gradle Redise 디펜던시 추가
> * [x]  Redis 설정, RefreshToken 객체, Repository 추가
> * [x]  refreshToken 생성 로직 변경
> * [x]  refreshToken 을 사용하여 accessToken 갱신 메소드 개발
> * [x]  validation 기능 개발
> 
> ## 변경 사항
> 다음과 같은 파일/부분을 수정했습니다:
> 
> * `src/main/kotlin/mara/server/�config/redis/*.kt`: redis, refreshToken 설정 추가
> * `src/main/kotlin/mara/server/domain/user/*.kt`: refreshToken 관련 로직 수정
> 
> ## 관련 이슈
> 이 PR과 관련된 이슈: [MARA-56](https://alsehf0316.atlassian.net/browse/56)
> 
> ## 테스트
> 다음과 같은 테스트를 수행했습니다:
> 
> * 단위 테스트: swagger 사용 단위 테스트 수행

해당 로직 반영 했습니다.

2024-02-15 08:40 UTC, Jiwon-cho commented
> 회의 내용 요약드립니다..! 💪💪
> 
> ```mermaid
> graph TD;
>     시작["API 호출"] --> 조건1{AccessToken이 유효한가?};
>     조건1 -- Yes --> 수행5["정상 호출"] --> 종료;
>     조건1 -- No --> 조건2{RefreshToken이 유효한가?};;
>     조건2 -- Yes --> 수행3["신규 AccessToken 발급"] --> 수행5["정상 호출"] --> 종료;
>     조건2 -- No --> 에러["예외 발생"];
> 	종료["응답 반환, Header에 AccessToken, RefreshToken 넣어 반환"]
> ```

해당 로직 반영했습니다.

2024-02-16 00:22 UTC, jhkang1517 requested changes

2024-02-16 00:22 UTC, jhkang1517 commented on src/main/resources/application-dev.yml
> +  refresh-duration-mins: 200000
0이 하나 더 들어간 것 같습니다. `200000` -> `20000` 😇

2024-02-16 00:22 UTC, jhkang1517 commented on src/main/kotlin/mara/server/auth/jwt/JwtProvider.kt
> +        } catch (ex: ExpiredJwtException) {
밑처럼 이 부분에도 `Token`이 만료되었다는 의미의 `log`가 필요할 것 같습니다! 💡💡

2024-02-16 02:02 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/auth/jwt/JwtProvider.kt
> +        } catch (ex: ExpiredJwtException) {
적용했습니다.

2024-02-16 02:03 UTC, Jiwon-cho commented on src/main/resources/application-dev.yml
> +  refresh-duration-mins: 200000
변경 하는김에 정확히 2주가 되는 20160 분으로 변경했습니다.

2024-02-16 02:05 UTC, jhkang1517 approved these changes
고생하셨습니다!! 👏👏

2024-02-16 02:05 UTC, merged