MARA-67 : Figma 화면설계서 기반 기능 점검을 통한 리팩토링 작업 수행
DDD-Community/mara-server pull request #28
Opened 2024-02-17 00:57 UTC by jhkang1517

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- Figma 화면설계서 기반 기능 점검을 통한 리팩토링 작업 수행

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/domain/refrigerator/*.kt`

  - [x] `@Transaction` 어노테이션 적용 
  - [x] 불필요하게 긴 Repository 메소드 이름 변경
  - [x] 공통으로 사용되는 코드 메소드 분리 'getCurrentLoginUserRefrigeratorList'
  - [x] `updateRefrigerator` -> `deleteRefrigerator` 오타 수정
  - [x] SpringDoc 기반 Swagger Document 어노테이션 추가

## 관련 이슈
이 PR과 관련된 이슈: [MARA-67](https://alsehf0316.atlassian.net/browse/MARA-67)

2024-02-18 13:54 UTC, Jiwon-cho reviewed
설명 부분은 잘 작성해주셔서 추가적으로 말씀드릴껀 없습니다. 다만, queryDsl 적용 부분에 있어서 조정이 좀 필요할것 같아, 제가 올리는 pr 확인 후 같이 얘기 나눠봐야 할것 같습니다.

2024-02-18 13:54 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/config/querydsl/QueryDslConfig.kt
> +@Configuration
해당 config 파일 제가 올리는 pr 에도 있어 이 파일에 대한 조율이 필요할것 같습니다.

2024-02-18 13:54 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/ingredient/IngredientDetailQuerydslRepository.kt
> +class IngredientDetailQuerydslRepository(
queryDsl 적용을 위한 repository 리팰토링에 대해서도,조정이 필요할것 같습니다. 제가 올리는 pr 확인후 의견 부탁드립니다.

2024-02-19 05:05 UTC, jhkang1517 commented on src/main/kotlin/mara/server/config/querydsl/QueryDslConfig.kt
> +@Configuration
#34 해당 PR 확인 후 적용했습니다!

2024-02-19 05:06 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/ingredient/IngredientDetailQuerydslRepository.kt
> +class IngredientDetailQuerydslRepository(
#34 해당 PR 확인 후 적용했습니다! 🌱🌱

2024-02-19 13:14 UTC, Jiwon-cho requested changes
추가적으로 이전 프로젝트 할 때 리뷰 받았던 사항인데, JpaRepository를 상속한 인터페이스를 작성하면, 해당 인터페이스에 @Repository 어노테이션을 추가하지 않아도 Spring이 자동으로 빈으로 등록해주기 때문에 @Repository 를 따로 추가하지 않아도 됩니다.
리뷰 확인 답변 부탁드립니다.

2024-02-19 13:14 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +interface CustomFriendshipRepository {
저는 기본 repositoy에 customRepository를 상속해서 기본 repository만 서비스에 선언해서 썼는데 따로 상속안하고 해당 레포를 서비스에 따로 선언한 이유가 있을까요 ?

2024-02-19 13:14 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
> +class CustomIngredientDetailRepositoryImpl(
위와 동일한 이유로 질문드립니다.

2024-02-19 13:14 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserRepository.kt
> +@Repository
위와 동일합니다.

2024-02-19 13:49 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +interface CustomFriendshipRepository {
사용자가 코드를 볼 때 커스텀한 메소드를 사용했는지, 일반 JPA 레포지토리 지원 메소드를 사용했는지 구분하고자 넣었는데, 좀 더 생각해보니 오히려 코드 가독성을 해치는 것 같습니다! 해당 내용 반영했습니다! 💪💪

2024-02-19 13:49 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/ingredient/IngredientDetailRepository.kt
> +class CustomIngredientDetailRepositoryImpl(
반영 완료! 🛠️

2024-02-19 13:49 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserRepository.kt
> +@Repository
반영 완료! 🛠️

2024-02-19 14:18 UTC, Jiwon-cho requested changes
마지막 리뷰입니다. 보고 의견주세요.

2024-02-19 14:18 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +    private val query: JPAQueryFactory
이 부분 제 리뷰에서 답을 못남겼는데, 저는 이게 query를 만들어주는 애라, queryFactory란 이름을 생각한건데, 어떻게 생각하시나요

2024-02-19 14:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/friend/FriendshipRepository.kt
> +    private val query: JPAQueryFactory
`query` -> `queryFacotry` 변경 했습니다!

2024-02-19 14:32 UTC, Jiwon-cho approved these changes
굳

2024-02-20 05:37 UTC, merged