feat: share 페이징 처리, queryDsl 적용
DDD-Community/mara-server pull request #34
Opened 2024-02-18 15:45 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- share 페이징 처리
- queryDsl 적용
- CustomRepository, CustomRepositoryImpl 추가
- share, user controller 설명 작성

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/domain/user/UserController`: 나눔 내역 페이징 처리 적용
- `src/main/kotlin/mara/server/domain/share/**`: 페이징 처리를 위한 queryDsl 적용, CustomRepository, CustomRepositoryImpl 추가

## 관련 이슈
이 PR과 관련된 이슈: [MARA-69](https://alsehf0316.atlassian.net/browse/69)

## 테스트
다음과 같은 테스트를 수행했습니다:
- 단위 테스트:  Swagger 를 이용한 기능  테스트 진행

## 리뷰어 참고 사항
- queryDsl 적용을 위한 부분에서도 조정이 필요할것 같아 리뷰 하면서 의견 교류가 필요할것 같습니다.

2024-02-19 01:25 UTC, jhkang1517 requested changes
리뷰 완료했습니다! 코멘트 답변 부탁드립니다~ 😄😄

2024-02-19 01:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/config/querydsl/QueryDslConfig.kt
> +    private val em: EntityManager,
해당 방식처럼 생성자 주입 방식으로 제 코드도 변경하겠습니다! 🦎🦎

2024-02-19 01:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareController.kt
> +    fun getAllShareList(pageable: Pageable, @RequestParam("sortBy") sortBy: String): CommonResponse<Page<ShareResponse>> {
`pageable` 에 `sort` 파라미터 가 있는데 이걸 활용하는건 어떠신가요? 🗝️

2024-02-19 01:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareRepository.kt
> +    private val queryFactory: JPAQueryFactory,
저는 `JPAQueryFactory` 에서 만들어진 `query` 라는 느낌으로 `queryFactory` 가 아닌 `query` 로 선언을 했는데, 이런 방식에 대해서는 어떻게 생각하시나요? 🌱🌱

2024-02-19 01:25 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareRepository.kt
> +    fun findAllMyFriendsShare(pageable: Pageable, sortBy: String, user: User): Page<Share>
JPA 메소드 네이밍 방식이 제가 구현한 코드보다 더 좋은 것 같습니다! 해당 네이밍 방식으로 적용하겠습니다! 🦎🦎

2024-02-21 06:35 UTC, jhkang1517 reviewed
pageable에서 sort 는 List<>로 들어와서 처리되기 때문에, 해당 타입의 고려가 필요할 듯 싶습니다..! 😭😭

2024-02-21 06:35 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareRepository.kt
> +            sortBy = order.property
해당 방식으로 구현하게 되면 `sortBy`는 `List<>` 형태가 아니게 되지 않나요..? 🤔🤔

2024-02-21 07:40 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareRepository.kt
> +            sortBy = order.property
sortBy 는 pageable 에 담긴 sort(List) 에서 정렬 시킬 값을 할당받는 변수 입니다.

2024-02-21 08:01 UTC, jhkang1517 submitted a review, later dismissed
고생하셨습니다! 👏👏

2024-02-21 08:03 UTC, jhkang1517 submitted a review, later dismissed
💡💡

2024-02-21 12:20 UTC, closed without merging