MARA-84: 유저 프로필 수정, 나눔 목록 , 상세 dto 분리, 신청, 생성 유무 확인 파라미터 추가
DDD-Community/mara-server pull request #47
Opened 2024-02-25 10:18 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- 유저 프로필 수정 api 개발
- 나눔 목록 , 상세 dto 분리
- 신청, 생성 유무 확인 파라미터 추가

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/domain/user/User.kt`: 업데이트 method 추가
- `src/main/kotlin/mara/server/domain/share/*`: 나눔 목록 , 상세 dto 분리, 신청, 생성 유무 확인 파라미터 추가

## 관련 이슈
이 PR과 관련된 이슈: [MARA-84](https://alsehf0316.atlassian.net/browse/84)

## 테스트
다음과 같은 테스트를 수행했습니다:
- 단위 테스트: swagger를 사용하여 단위 테스트 진행 함

2024-02-25 12:57 UTC, jhkang1517 requested changes
리뷰 완료했습니다! 💪💪

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +    val thumbNailImage: String,
찾아보니 `thumbnail` 전체가 하나의 단어인 것 같습니다! `thumbNail` -> `thumbnail` 수정 부탁드려용 🛠️🛠️

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        shareTime = share.shareTime.truncatedTo(ChronoUnit.MINUTES),
`truncatedTo(ChronoUnit.MINUTES)` 이건 사용하신 이유가 뭔가요?? 🧐

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +    val peopleCnt: Int,
`peopleCnt` -> `peopleCount` 변경 필요합니다! 🛠️

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        isMine = isMine
`isMine` 이 필요한 이유는 무엇인가요??? 🧐

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
`updateRequest` -> `userUpdateRequest` 변경해주세요! 🛠️

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun updateUser(@RequestBody updateRequest: UserUpdateRequest): CommonResponse<Boolean> {
마찬가지로 updateRequest -> userUpdateRequest 변경해주세요! 🛠️

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
추가적으로.. 아직까지 `User` 의 값을 다르게 업데이트 하는 메소드는 없으니, `updateUserInfo` 보다는 `update` 혹은 `updateUser` 가 좋을 것 같은데 해당 사항에 대한 의견 부탁드립니당.. 만약 이런 식으로 구체화하는게 더 일반적인 방식이라면 제 코드에도 반영해야할 것 같습니다!

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val updatedUser = userRepository.save(user)
이 부분도 리뷰하다 뒤늦게 알게된 부분인데요..! 저 같은 경우에는 update 이후에는 update된 객체를 리턴하고 있는데, 작성하신 share 쪽도 확인해보니 업데이트 되었다는 `Boolean` 값을 리턴하고 계시더라구요. 이 부분은 논의하여 통일성있게 작성해야 할 것 같습니다..! 🫡🫡

2024-02-25 12:57 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
>          val me = userService.getCurrentLoginUser()
지금까지 저희가 작성한 코드에서는 `val me` 보다는 `val user` 혹은 `val currentLoginUser` 를 사용하고 있습니다..! 통일 부탁드립니다~

2024-02-25 15:07 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +    val thumbNailImage: String,
반영했습니다.

2024-02-25 15:09 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        shareTime = share.shareTime.truncatedTo(ChronoUnit.MINUTES),
원래는 프론트에서 초를 떼서 보내달라고 해서 작성했던건대, 해당 코드는 초의 값을 00으로만 바꿔주기만 해서 일단 제거 했습니다. 추가적으로 이 부분은 다시 생각해보니 프론트 단에서 처리하는게 낫지 않을까 해서 한번 얘기해보고 다시 결정하려고합니다.

2024-02-25 15:09 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +    val peopleCnt: Int,
변경했습니다.

2024-02-25 15:11 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        isMine = isMine
내가 만든 게시글인지 확인 하는 변수입니다. 프론트에서 내 게시글인지에따라 나눔 글의 기능의 활성화/비활성화를 시키는 키가 필요하다고 해서 추가했습니다.

2024-02-25 15:11 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
변경했습니다.

2024-02-25 15:11 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserController.kt
> +    fun updateUser(@RequestBody updateRequest: UserUpdateRequest): CommonResponse<Boolean> {
변경했습니다.

2024-02-25 15:12 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
댜른 정보는 다 불변될 정보이기에, 변경 되는 두가지의 값이 전부라고 생각해서 해당 메소드명으로 작성했던건데, 이 부분에 대해서 어떻게 생각하는지 의견 부탁드립니다.

2024-02-25 15:13 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val updatedUser = userRepository.save(user)
업데이트를 한 후 프론트에서는 업데이트가 성공했는지 유무만 필요하고 객체 정보를 넘길 필요까지는 없는 것 같아서 이처럼 코드를 작성했습니다.  이 부분에 대해서 어떻게 생각하시나요?

2024-02-25 15:13 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareService.kt
>          val me = userService.getCurrentLoginUser()
변경했습니다.

2024-02-25 16:23 UTC, jhkang1517 reviewed
코멘트 남겼습니다! 해당 부분 확인부탁드립니다~ ✅

2024-02-25 16:23 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        isMine = isMine
피그마로 확인해보니 말씀하신대로 자신이 작성한 나눔 글에 대한 상호작용에 있어서 애매한 부분이 있네요.. 이 부분은 기간이 얼마 남지 않은 걸 고려하면 수정은 어려워 보이지만, 기획에서 자신의 글이 보여지는 경우에는 어떤 상호작용을 의도하셨는지에 대해 확인은 해놓아야 할 것 같습니다. 해당 부분 확인 해주세요! 😵‍💫😵‍💫

2024-02-25 16:23 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
저는 코드가 `user.update()` (사용자 업데이트) 로만 작성되어 있어도, 이를 이해하는데 문제가 없다고 생각합니다. `user.updateUserInfo()` (사용자 사용자 정보 업데이트) 의 경우에는 불필요하게 user가 반복되는 느낌이라서.. 해당 관점에서 의견 드립니다. 😶‍🌫️😶‍🌫️

2024-02-25 16:23 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val updatedUser = userRepository.save(user)
레퍼런스를 찾아보니 PUT 을 수행하고 객체를 리턴해야하는지, 단순 상태값만 리턴해야하는지는 선택의 문제기 때문에 어느 하나를 콕 집어서 통일시킬 필요는 없을 것 같습니다. 그냥 지금 그대로 가도 좋을 것 같습니다! 🏃‍♂️🏃‍♂️

_Reference : https://www.rfc-editor.org/rfc/rfc7231#section-4.3.4_

2024-02-25 16:23 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        shareTime = share.shareTime.truncatedTo(ChronoUnit.MINUTES),
해당 부분 결정 되면 공유 부탁드립니다! 🌿🌿

2024-02-26 04:34 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/share/ShareDto.kt
> +        isMine = isMine
본인 글이 면 상세 들어갔을 때 신청 버튼을 비활성화 시킬 계획인거 같아, 이 기능을 위해 사용될꺼 같습니다.

2024-02-26 04:45 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
저는 반대로 메소드명이 그냥 update 라고만 되있으면, 다른 엔티티의 update 메소드와 비교해서 이름이 중복되기 떄문에, 추후 수정이 필요하거나 리팩토링이 필요할 때, 유지 보수 차원에서 더 어려워지지 않을까 해서.. 음.. 잘모르겠네요 .. 🤔🤔

2024-02-26 04:45 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/UserService.kt
> +        val updatedUser = userRepository.save(user)
그럼 현 상태로 유지 하겠습니다.

2024-02-26 05:24 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
`user.update` 만으로도 충분히 사용자가 업데이트 된다는 걸 인지할 수 있는데 굳이 `user.updateUser` 가 필요할까요? 만약에 `update` 가 한 개가 아니라 여러개가 될 경우에는 `updateInfo`, `updateStatus` 등이 필요할 것 같지만.. 그 전까지는 `update`로 유지하는 것이 좋다는 의견 드립니다. 어차피 리팩토링은 메소드 체이닝으로 타고 들어가서 상관없을 것 같구요..! 🧐

2024-02-26 05:45 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
제가 말한 여러가지 메소드는 다른 엔티티 메소드들도 모두 update 라고 되있을 때를 가정해서 말한거였습니다. 저 같은 경우엔, 전체 겁색을 통해서 메소드를 찾기도 하는데, update 라는 이름을 가진 메소드가 여러개 있다면 바로 찾기 힘들것 같아 그렇습니다. 물론 메소드 체이닝을 타고 들어가서 찾을 수도 있지만, 저는 개인적으로 메소드명은 구체적인게 좋다고 생각합니다. 구체적으로 선언 해두면 차후 따로 바꿀 필요가 적을꺼 같기도 하구요. 사실 변수명이란게 전반적으로 통용 되는 네이밍 컨밴션 과 팀의 네이밍 컨밴션을 고려해서 하는거라.. 결론적으론 그럼 updateInfo 정도는 어떨까요? 의견 부탁드립니다.

2024-02-26 05:49 UTC, jhkang1517 commented on src/main/kotlin/mara/server/domain/user/User.kt
> +    fun updateUserInfo(updateRequest: UserUpdateRequest) {
좋습니다!! 💪💪

2024-02-26 06:05 UTC, jhkang1517 approved these changes
고생하셨습니다! 👏👏

2024-02-26 06:05 UTC, merged