Mara-88: 환경 별 리다이랙트 uri 구분을 위한 status 값 추가, 나눔 변수 추가,수정, 전역 예외 처리, 커스텀 예외 클래스 추가
DDD-Community/mara-server pull request #49
Opened 2024-02-27 14:38 UTC by Jiwon-cho

# Pull Request

## 작업 내용
이 PR은 다음과 같은 작업을 포함하고 있습니다:
- 환경 별 리다이랙트 uri 구분을 위한 status 값 추가
- 나눔 변수 추가,수정(thumNailImage -> thumnailImage , ShareDeatilRespons 에 isApplied 추가)
- 전역 예외 처리, 커스텀 예외 클래스 추가

## 변경 사항
다음과 같은 파일/부분을 수정했습니다:
- `src/main/kotlin/mara/server/auth/** `: google,kakaoClient, ClientConfig 수정
- `src/main/kotlin/mara/server/common/**`: 전역 예외처리 클래스, 커스텀 예외 집합 클래스, CommonResponse 내 badRequest 추가 

## 관련 이슈
이 PR과 관련된 이슈: [MARA-88](https://alsehf0316.atlassian.net/browse/88)

## 특이 사항/주의 사항
- 커스텀 예외 클래스를 하나만 넣어놓기는 했지만, 만들어놓은 클래스에 커스텀 예외 클래스 모아둘 계획

## 테스트
다음과 같은 테스트를 수행했습니다:
- 단위 테스트: Swagger 를 통한 단위테스트 진행

2024-02-28 01:18 UTC, jhkang1517 requested changes
리뷰 남겼습니다! 🦾🦾

2024-02-28 01:18 UTC, jhkang1517 commented on src/main/kotlin/mara/server/auth/google/GoogleApiClient.kt
> +    fun getRedirectUri(status: String): String {
`GoogleApiClient` 와 `KakaoApiClient` 에서 `DeployStatus.LOCAL` 값을 제외하곤 코드가 중복되는 것 같은데, 하나로 합치는건 어떠신가요? 🗝️

2024-02-28 01:18 UTC, jhkang1517 commented on src/main/kotlin/mara/server/common/CommonResponse.kt
> +fun badRequest(message: String): ResponseEntity<CommonResponse<Any>> = ResponseEntity
몇 가지 제안 드리고자 합니다..!

1. `CommonResponse<Any>` 보다는 `<T>` 를 사용하는 건 어떠신가요? 굳이 슈퍼타입인 `Any`를 사용해야할 필요는 없는 것 같습니다..!

2. `badRequest` 와 같이 특정 HTTP status 를 리턴하는 함수 보다는 HTTP status 값과 message 값을 파라미터로 받아서 처리하는` fun fail`, 혹은 `fun error` 등의 함수로 이름을 바꾸는건 어떠신가요?

3. 현재 구조로 개발하면 `CommonResponse` 에서 custom exception message만 사용이 될 것 같은데, 예외를 발생시킨 데이터도 data에 넣어서 return 하는 건 어떠신가요? 파라미터에 추가하면 될 것 같습니다!

해당 내용에 대한 의견 부탁드립니다~ 🎢🎢

2024-02-28 14:35 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/auth/google/GoogleApiClient.kt
> +    fun getRedirectUri(status: String): String {
변경했습니다.

2024-02-28 14:37 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/common/CommonResponse.kt
> +fun badRequest(message: String): ResponseEntity<CommonResponse<Any>> = ResponseEntity
1. 변경했습니다.
2. 변경했습니다.
3. 따로 데이터 변수를 넣지는 않았고, 에러를 낸 변수를 메세지에 담는 식으로 변경해봤습니다.

2024-02-28 15:36 UTC, Jiwon-cho commented on src/main/kotlin/mara/server/common/CommonResponse.kt
> +fun badRequest(message: String): ResponseEntity<CommonResponse<Any>> = ResponseEntity
다시 수정했습니다.

2024-02-29 15:50 UTC, jhkang1517 approved these changes
수고하셨습니다!! 👏👏

2024-02-29 15:50 UTC, merged